Repository LeeByeongMuk/nextjs-starter-kit, pull requests merged in 2024-09, with the labels that each got.

#79 feature: 유저 CRUD API 추가
  .env.example
  README.md
  compose.yaml
  package.json
  prisma/migrations/20240906150506_/migration.sql
  prisma/migrations/migration_lock.toml
  prisma/schema.prisma
  public/mockServiceWorker.js
  src/app/types/env.d.ts
  src/server/app.ts
  src/server/controllers/users_controllers.ts
  src/server/models/token_models.ts
  src/server/models/users_models.ts
  src/server/routes/posts.ts
  src/server/routes/users_routes.ts
  src/server/services/token_services.ts
  src/server/services/users_services.ts
  src/server/utils/errorHandling.ts
  src/server/utils/prisma.ts
  tsconfig.json
Labels: enhancement

#81 fix: API 수정 대응
  public/mockServiceWorker.js
  src/app/(auth)/account/page.tsx
  src/app/(auth)/signin/page.tsx
  src/app/(auth)/signup/page.tsx
  src/app/api/auth/[...nextauth]/route.ts
  src/app/api/auth/index.ts
  src/app/api/post.ts
  src/app/components/Post/ListFilter/index.tsx
  src/app/components/Post/ListTable.tsx
  src/app/components/Post/Pagination.tsx
  src/app/components/Post/PostDetail.tsx
  src/app/constants/post.ts
  src/app/hooks/post/useCreatePost.ts
  src/app/hooks/post/usePost.ts
  src/app/hooks/post/usePostList.ts
  src/app/hooks/post/useReplaceSearchParams.ts
  src/app/hooks/post/useSearchFilters.ts
  src/app/hooks/post/useUpdatePost.ts
  src/app/hooks/post/useUpdatePostResource.ts
  src/app/post/PostList.spec.tsx
  src/app/post/[id]/update/page.tsx
  src/app/post/create/page.tsx
  src/app/types/api/auth.ts
  src/app/types/api/common.ts
  src/app/types/api/pagination.ts
  src/app/types/api/post.ts
  src/app/types/form/auth.ts
  src/app/types/form/post.ts
  src/app/types/nextAuth.d.ts
  src/server/controllers/posts_controllers.ts
  src/server/models/posts_models.ts
  src/server/models/users_models.ts
  src/server/services/posts_services.ts
  src/server/services/users_services.ts
Labels: bug, enhancement

#86 fix: 백앤드 연동 디버깅
  .github/workflows/build.yml
  src/app/api/post.ts
  src/app/components/Post/List/EmptyItem.tsx
  src/app/components/Post/List/Item.tsx
  src/app/components/Post/List/LoadingList.tsx
  src/app/components/Post/List/index.tsx
  src/app/components/Post/ListTable.tsx
  src/app/components/Post/Pagination.tsx
  src/app/hooks/post/useDeletePost.ts
  src/app/post/[id]/page.tsx
  src/app/post/page.tsx
  src/app/types/api/post.ts
  src/app/utils/api.ts
  src/server/app.ts
  src/server/controllers/posts_controllers.ts
  src/server/models/posts_models.ts
  src/server/models/users_models.ts
  src/server/services/posts_services.ts
  src/server/services/users_services.ts
  src/server/utils/errorHandling.ts
Labels: bug, enhancement

#87 feature: GitHub Actions, GPT Review 수정
  .github/workflows/review.yml
Labels: review

#88 chore: 로컬 개발환경 추가
  .dockerignore
  .env.example
  .gitignore
  Dockerfile
  README.md
  compose.yaml
  package-lock.json
  package.json
Labels: documentation, enhancement
